config/routes.rb
Flockapp::Application.routes.draw do
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :conferences do
    resources :activities
    collection do
      post 'update_location'
    end
  end

  resources :speakers, except: [:new] do
    collection do
      get 'resources'
    end
  end
  resources :airports, only: [:show]
  resources :hotels,   only: [:show, :new, :create]

  resources :organizers do
  collection do
    get 'resources'
  end
  end

  get "welcome/landing"
  get "static_pages/about", path: "/about"

  root "welcome#landing"

  

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :activities
  paginates_per 10

  # These may no longer be needed if we are just going to use geocoding to show nearby ones
  has_many :airports
  has_many :hotels

  geocoded_by :location
  after_validation :geocode, :if => lambda { location_changed? && (latitude.blank? || longitude.blank?) }

  scope :on_date, lambda { |date| where("start_date <= ? and end_date >= ?", date, date) }

  scope :upcoming, lambda { where("start_date >= ?", Date.today) }

  validates :safety_policy, :format => { with: URI::regexp(%w(http https)), :message => "must be a URL to your policy" }, allow_blank: true

  def nearby_airports(distance = 20)
    Airport.large_airports.near(location, distance)
  end

  def nearby_hotels(distance = 20)
    Hotel.near(location, distance)
  end

  def self.search(fields)
    scopes = {
      name:          where(["name like ?", "%#{fields[:name]}%"]),
      category:      where(["category like ?", "%#{fields[:category]}%"]),
      childcare:     where({childcare: ActiveRecord::ConnectionAdapters::Column.value_to_boolean(fields[:childcare])}),
      safety_policy: where("safety_policy is not null and safety_policy <> ''"),
      location:      near(fields[:location]),
      date:          on_date(fields[:date]),
    }

    scopes.keys.inject(self.all) do |results, field|
      if fields[field].present? then
        results.merge(scopes.fetch(field))
      else
        results
      end
    end
  end
end

app/controllers/conferences_controller.rb
class ConferencesController < ApplicationController
  before_action :set_conference, only: [:show, :edit, :update, :destroy]

  # GET /conferences
  # GET /conferences.json
  def index
    @conferences = params[:search] ? Conference.search(params[:search]) :  Conference.all
    @conferences = @conferences.upcoming.order(:start_date).page(params[:page])
    params[:search] ||= {}
  end

  # GET /conferences/1
  # GET /conferences/1.json
  def show
  end

  # GET /conferences/new
  def new
    @conference = Conference.new
  end

  # GET /conferences/1/edit
  def edit
  end

  # POST /conferences
  # POST /conferences.json
  def create
    @conference = Conference.new(conference_params)

    respond_to do |format|
      if @conference.save
        format.html { redirect_to @conference, notice: 'Conference was successfully created.' }
        format.json { render action: 'show', status: :created, location: @conference }
      else
        format.html { render action: 'new' }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conferences/1
  # PATCH/PUT /conferences/1.json
  def update
    respond_to do |format|
      if @conference.update(conference_params)
        format.html { redirect_to @conference, notice: 'Conference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @conference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conferences/1
  # DELETE /conferences/1.json
  def destroy
    @conference.destroy
    respond_to do |format|
      format.html { redirect_to conferences_url }
      format.json { head :no_content }
    end
  end

  def update_location
    @latitude, @longitude = Geocoder.coordinates(params[:location])

    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conference
      @conference = Conference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conference_params
      params.require(:conference).permit(:name, :start_date, :end_date, :location, :category, :safety_policy, :childcare, :latitude, :longitude, :airport_ids => [], :hotel_ids => [])
    end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  def by_month(conferences)
    conferences.group_by { |conference| conference.start_date ? conference.start_date.strftime("%B %Y") : "" }
  end

  def start_day_of_conference(conference)
    conference.start_date ? conference.start_date.day : ""
  end

  def day_class(conference)
    start_day_of_conference(conference) < 10 ? "day-single" : "day-double"
  end

  def safety_policy_link(conference)
    conference.safety_policy.present? ? link_to(@conference.safety_policy, @conference.safety_policy) : "None"
  end
end

app/views/conferences/_form.html.erb
<%= form_for(@conference) do |f| %>
  <% if @conference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conference.errors.count, "error") %> prohibited this conference from being saved:</h2>

      <ul>
      <% @conference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :latitude %>
  <%= f.hidden_field :longitude %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :safety_policy %><br>
    <%= f.text_field :safety_policy %>
  </div>
  <div class="field">
    <%= f.label :childcare %><br>
    <%= f.check_box :childcare %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conferences/_map.html.erb
<div class="row">
  <div class="column one-third">
    <div id="places">
      <ul class="list">
      <li id="airport" class="place-title"><strong>Airports:</strong></li>
      <li id="atm" class="place-title"><strong>ATM:</strong></li>
      <li id="car_rental" class="place-title"><strong>Car Rental</strong></li>
      <li id="grocery_or_supermarket" class="place-title"><strong>Groceries/Supermarket</strong></li>
      <li id="food" class="place-title"><strong>Food</strong></li>
      <li id="restaurant" class="place-title"><strong>Restaurant</strong></li>
      <li id="subway_station" class="place-title"><strong>Subway Station</strong></li>
      <li id="train_station" class="place-title"><strong>Train Station</strong></li>
    </ul>
    </div>
  </div>
  <div class="column two-third">
    <div id="map-canvas"></div>
  </div>

  <div class="clear"></div>
</div>

app/views/conferences/_nearby_airports.html.erb
<% @conference.nearby_airports.each do |airport| %>
  <%= link_to airport.name, airport_path(airport, conference_id: @conference.id) %>
<% end %>

app/views/conferences/_nearby_hotels.html.erb
<% @conference.nearby_hotels.each do |hotel| %>
  <%= link_to hotel.name, hotel_path(hotel, conference_id: @conference.id) %>
<% end %>

<% # We should probably do this as an inline form so the hotel can be added at the same time %>
<%= link_to 'New Hotel', new_hotel_path %>

app/views/conferences/edit.html.erb
<h1>Editing <%= @conference.name %></h1>

<%= render 'form' %>

<%= link_to 'Show', @conference %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/index.html.erb
<section class="container">
<h1>Upcoming Events</h1>
<% by_month(@conferences).each do |month, conferences| %>
  <table class="schedule">
    <thead>
      <tr>
        <th colspan="2">
          <h2><%= month %></h2>
          <div class="pushpin">
            <%= link_to image_tag("pushpin.gif"), new_conference_path %>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      <% conferences.each do |conference| %>
        <tr class="event">
          <th class="date">
            <div class="calendar-icon"><h2 class="<%= day_class(conference) %>"><%= start_day_of_conference(conference) %></h2></div></th>
          <td>
            <h3><%= link_to conference.name, conference_path(conference) %></h3>
            <p><%= conference.location %></p></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</section>

<h1>
<%= paginate @conferences %>
</h1>

app/views/conferences/new.html.erb
<h1>New conference</h1>

<%= render 'form' %>

<%= link_to 'Back', conferences_path %>

app/views/conferences/show.html.erb
<section class="profile">
  <div class="container">
    <p id="notice"><%= notice %></p>

    <script type="text/javascript" charset="utf-8">
window.conference = <%=
{name: @conference.name,
 location: @conference.location,
 longitude: @conference.longitude,
 latitude: @conference.latitude,
}.to_json.html_safe
%>;
console.log(conference);
    </script>

    <h1><%= @conference.name %></h1>
<div class="row">
  <p>Happening <strong><%= @conference.start_date %></strong> through <strong><%= @conference.end_date %></strong> in <strong><%= @conference.location %></strong></p>
  <% if @conference.category.present? %>
    <p>The category is <%= @conference.category %></p>
  <% end %>
  <p><strong>Safety Policy:</strong> <%= safety_policy_link(@conference) %></p>
  <% if @conference.childcare %><p><strong>Offers Childcare</strong></p><% end %>

</div>
<%= render "map" %>

<%= link_to 'Edit', edit_conference_path(@conference) %> |
<%= link_to 'Back', conferences_path %>

app/views/conferences/update_location.js.erb
$('conference_latitude').value(<%= @latitude %>);
$('conference_longitude').value(<%= @longitude %>);

latLong = new google.maps.LatLong(<%= @latitude %>, <%= @longitude %>);
console.log("update - location -");
ckim();