config/routes.rb
Flockapp::Application.routes.draw do
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :conferences do
    resources :activities
    collection do
      post 'update_location'
    end
  end

  resources :speakers, except: [:new] do
    collection do
      get 'resources'
    end
  end
  resources :airports, only: [:show]
  resources :hotels,   only: [:show, :new, :create]

  resources :organizers do
  collection do
    get 'resources'
  end
  end

  get "welcome/landing"
  get "static_pages/about", path: "/about"

  root "welcome#landing"

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"

  def coming_soon
  end

  def landing
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/landing.html.erb
<section id="speaker">
    <div class="row">
      <div class="column one-third">
        <div class="choice-badge">
          <%= image_tag "speaker.png" %>
        </div>
      </div>
      <div class="column two-third" id="speaker">
        <h1>Speaker</h1>
        <p>Are you a conference speaker? Would you like to become a conference speaker? <%= link_to "Sign up", new_user_registration_path %> with a speaker profile and you can add yourself to our list of <%= link_to "speakers", speakers_path %>. Adding yourself with a speaker profile means you will have a user profile that can list your past talks, your upcoming events,your slides, and more.</p>
        <p>We also have tons of resources for speakers.</p>
        <p><%= link_to "Find Out More", resources_speakers_path %>.</p>
      </div>
    </div>
  </section>

<section id="attendee">
    <div class="row">
      <div class="column one-third">
        <div class="choice-badge">
          <%= image_tag "attendee.png" %>
        </div>
      </div>
      <div class="column two-third">
        <h1>Attendee</h1>
        <p>Attending conferences can be a great time. We want to make sure you have the best experience possible, we have a list of conferences with lots of important information for each conference.</p>
        <p><%= link_to 'Find Out More', conferences_path %>.</p>
      </div>
    </div>
  </section>

<section id="host">
    <div class="row">
      <div class="column one-third">
        <div class="choice-badge">
          <%= image_tag "host.png" %>
        </div>
      </div>
      <div class="column two-third">
        <h1>Host</h1>
        <p>If you're going to putting on a conference there are lots of important things to factor in, or if you're just interested in how to put on a fantastic conference. We've compiled a ton of resources to make sure you put on a great conference.        
        <p>If you're looking for speakers for your conference, browse our <%= link_to 'list', speakers_path %>.</p>
        <p><%= link_to 'Find Out More', resources_organizers_path %>.</p>
      </div>
    </div>
  </section>