config/routes.rb
Flockapp::Application.routes.draw do
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :conferences do
    resources :activities
    collection do
      post 'update_location'
    end
  end

  resources :speakers, except: [:new] do
    collection do
      get 'resources'
    end
  end
  resources :airports, only: [:show]
  resources :hotels,   only: [:show, :new, :create]

  resources :organizers do
  collection do
    get 'resources'
  end
  end

  get "welcome/landing"
  get "static_pages/about", path: "/about"

  root "welcome#landing"

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :conference

  scope :alcohol_free, -> { where(alcohol: false) }
  scope :alcohol,      -> { where(alcohol: true) }
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_conference
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = @conference.activities
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = @conference.activities.build
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = @conference.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to [@conference, @activity], notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: [@conference, @activity] }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to [@conference, @activity], notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to conference_activities_url(@conference) }
      format.json { head :no_content }
    end
  end

  private
    def set_conference
      @conference = Conference.find(params[:conference_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = @conference.activities.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :description, :alcohol)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<tr>
  <td><%= activity.name %></td>
  <td><%= activity.description %></td>
  <td><%= link_to 'Show', conference_activity_path(@conference, activity) %></td>
  <td><%= link_to 'Edit', edit_conference_activity_path(@conference, activity) %></td>
  <td><%= link_to 'Destroy', conference_activity_path(@conference, activity), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/activities/_form.html.erb
<%= form_for([@conference, @activity]) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :alcohol %><br>
    <%= f.check_box :alcohol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', [@conference, @activity] %> |
<%= link_to 'Back', conference_activities_path(@conference) %>

app/views/activities/index.html.erb
<h1>Alcohol Free Activities</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <%= render @conference.activities.alcohol_free %>
  </tbody>
</table>

<br>

<h1>Alcohol Activities</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <%= render @conference.activities.alcohol %>
  </tbody>
</table>

<%= link_to 'New Activity', new_conference_activity_path(@conference) %>
<%= link_to 'Back', conference_path(@conference) %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', conference_activities_path(@conference) %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Alcohol:</strong>
  <%= @activity.alcohol %>
</p>

<%= link_to 'Edit', edit_conference_activity_path(@conference, @activity) %> |
<%= link_to 'Back', conference_activities_path(@conference) %>