config/routes.rb
Flockapp::Application.routes.draw do
  resources :profiles
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :conferences do
    resources :activities
    collection do
      post 'update_location'
    end
  end

  resources :speakers, except: [:new] do
    collection do
      get 'resources'
    end
  end
  resources :airports, only: [:show]
  resources :hotels,   only: [:show, :new, :create]

  resources :organizers do
  collection do
    get 'resources'
  end
  end

  get "welcome/landing"
  get "static_pages/about", path: "/about"

  root "welcome#landing"

  

end

app/models/speaker.rb
class Speaker < ActiveRecord::Base
  validates_format_of :url, :with => URI::regexp(%w(http https))
  validates_format_of :slides, :with => URI::regexp(%w(http https)), :allow_blank => true
  has_one :user


  def self.new_but_blank!
    speaker = new
    speaker.save(validate:false)
    speaker
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  before_filter :store_location
  before_filter :authenticate_user!, only: [:update, :delete, :create, :new, :edit]
  before_action :set_speaker, only: [:show, :edit, :update, :destroy]

  # GET /speakers
  # GET /speakers.json
  def index
    @speakers = Speaker.all
    @users = User.all
  end

  # GET /speakers/1
  # GET /speakers/1.json
  def show
    @speaker = Speaker.find(params[:id])
  end

  # GET /speakers/1/edit
  def edit
  end

  # POST /speakers
  # POST /speakers.json
  def create
    @speaker = Speaker.new(speaker_params.merge({:user_id => current_user.id }))
    respond_to do |format|
      if @speaker.save
        format.html { redirect_to @speaker, notice: 'Speaker was successfully created.' }
        format.json { render action: 'show', status: :created, location: @speaker }
      else
        format.html { render action: 'new' }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /speakers/1
  # PATCH/PUT /speakers/1.json
  def update
    respond_to do |format|
      if @speaker.update(speaker_params)
        format.html { redirect_to @speaker, notice: 'Speaker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @speaker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /speakers/1
  # DELETE /speakers/1.json
  def destroy
    @speaker.destroy
    respond_to do |format|
      format.html { redirect_to speakers_url }
      format.json { head :no_content }
    end
  end

  def resources
  end

  def store_location
    if (!request.fullpath.match("/users/") &&
        !request.xhr?)
      session[:previous_url] = request.fullpath
    end
  end

  def after_sign_in_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_update_path_for(resource)
    session[:previous_url] || root_path
  end

  def after_sign_out_path_for(resource)
    session[:previous_url] || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_speaker
      @speaker = Speaker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def speaker_params
      params.require(:speaker).permit(:first_name, :last_name, :url, :slides, :past_talks, :location, :user_id, :expertise, :upcoming_talks)
    end

end

app/helpers/speakers_helper.rb
module SpeakersHelper
  def gravatar_for_speaker(speaker)
    gravatar_image_tag(speaker.user.email.downcase, :alt => speaker.user.name, :class => "gravatar-speaker", :gravatar => {:size => 50 })
  end
end

app/views/speakers/_form.html.erb
<%= form_for(@speaker) do |f| %>
  <% if @speaker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@speaker.errors.count, "error") %> prohibited this speaker from being saved:</h2>

      <ul>
      <% @speaker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expertise %><br>
    <%= f.text_field :expertise %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :slides %><br>
    <%= f.text_field :slides %>
  </div>
  <div class="field">
    <%= f.label :past_talks %><br>
    <%= f.text_area :past_talks %>
  </div>
  <div class="field">
    <%= f.label :upcoming_talks %><br>
    <%= f.text_area :upcoming_talks %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/speakers/edit.html.erb
<% if user_signed_in? && @speaker == current_user.speaker %>
  <h1>Edit Speaker Profile</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @speaker %> |
  <%= link_to 'Back', speakers_path %>
<% else %>
  <p>You can't do that</p>
<% end %>

app/views/speakers/index.html.erb
<h1>All Speakers</h1>
<% @speakers.each do |speaker| %>
  <% if speaker.url %>
    <section class="container">
    <table class="schedule">
      <thead>
        <tr>
          <th colspan="2">
            <h2>Speakers</h2>
          </th>
        </tr>
      </thead>
      <tbody>
      <tr class="event">
        <th class="date">
          <div class="gravatar-speaker-list"><%= gravatar_for_speaker(speaker) %></div></th>
        <td>
          <h3><%= link_to h(speaker.user.name), profile_path(speaker.user) %></h3>
          <p>Areas of Expertise: <%= speaker.expertise %></p>
        </td>
      </tr>
      </tbody>
    </table>
  </section>
<% end %>
<% end %>

app/views/speakers/new.html.erb
<h1>New speaker</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>
  <%= link_to 'Edit profile', edit_profile_path(current_user.id) %> | 
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %> |
  <%= link_to "Login", new_user_session_path %>
<% end %>

<%= render 'form' %>

<%= link_to 'Back', speakers_path %>

app/views/speakers/resources.html.erb
<section class="profile">
  <div class="container">
    <h1>Resources for Speakers</h1>
<p>Speaking at conferences can be a very rewarding experience, but it can be kind of intimidating or scary. </p>
<p class="last">We've compiled a list of great resources that should help you get started and on your way to speaking at conferences</p>



<h2>General Advice for New Speakers</h2>
<ul class="list">
	<li><a href="http://ashedryden.com/blog/what-you-need-to-know-about-speaking-at-conferences">What You Need to Know About Speaking at Conferences</a> by <a href="http://www.ashedryden.com">Ashe Dryden</a>
	<li><a href="http://www.nczonline.net/blog/2013/01/10/advice-for-new-and-aspiring-technical-speakers/">Advice for New and Aspiring Technical Speakers</a> by <a href="http://www.nczonline.net/">Nicholas C. Zakas</a>
	<li><a href="http://jenmyers.net/confessions-of-a-semi-amateur-speaker.html">Confessions of a Semi-Amateur Speaker</a> by <a href="http://jenmyers.net">Jen Myers</a>
	<li><a href="http://julieannhorvath.com/2012/11/03/becoming-a-speaker.html">On Motivation: Becoming a Speaker</a> by <a href="http://julieannhorvath.com">Julie Ann Horvath</a>
	<li><a href="http://neil-gaiman.tumblr.com/post/41653204206/6-tips-for-speaking-in-public">Six Tips for Speaking in Public</a> by <a href="http://neil-gaiman.tumblr.com">Neil Gaiman</a>
	<li><a href="http://rubyrogues.com/064-rr-presenting-at-conferences/">Presenting at Conferences</a> on the <a href="http://rubyrogues.com">Ruby Rogues Podcast</a>
	<li><a href="https://docs.google.com/document/d/1PMhJJP7IQYiFtqxnS_h1EHPo1fBGoddcWLXaMaxx3Yc/edit">Speaker Notes</a> by <a href="http://www.devchix.com">DevChix</a>
</ul>



<h2>Writing a Proposal</h2>
	<ul class="list">
		<li><a href="http://blowmage.com/2013/01/24/writing-conf-proposals">Writing Conference Proposals</a> by <a href="http://blowmage.com/">Mike Moore</a>
		<li><a href="http://benramsey.com/blog/2012/11/writing-an-effective-talk-proposal/">Writing an Effective Talk Proposal</a> by <a href="http://benramsey.com/">Ben Ramsey</a>
	</ul>

	<h2>Putting on a Great Presentation</h2>
	<ulc lass="list">
		<li><a href="http://gazit.me/2012/12/05/designing-presentations.html">Designing Presentations</a> by <a href="http://gazit.me">Idan Gazit</a>
		<li><a href="http://blog.josephwilk.net/presentations/a-developers-guide-to-creating-presentations.html">A Developers Guide to Creating Presentations</a> by <a href="http://blog.josephwilk.net">Joseph Wilk</a>
		<li><a href="http://www.techwell.com/2012/09/creating-engaging-presentation">Creating an Engaging Presentation</a> by <a href="http://www.techwell.com/users/rick-scott">Rick Scott</a>
		<li><a href="http://toobigtotweet.tumblr.com/post/15575457908/suggestions-for-writing-a-good-conference-presentation">Suggestions for Writing a Good Conference Presentation</a> by <a href="http://toobigtotweet.tumblr.com">Adam Connor</a>
		<li><a href="http://www.ted.com/talks/nancy_duarte_the_secret_structure_of_great_talks.html">The Secret Structure of Great Talks</a> by <a href="http://www.duarte.com/">Nancy Duarte</a>
	</ul>

<h2>Other Useful Speaking Resources</h2>
	<ul class="last-ul list">
		<li><a href="http://weareallaweso.me/">We Are All Awesome</a>
		<li><a href="http://www.speakinghacks.com/">Speaking Hacks</a>
	</ul>

app/views/speakers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @speaker.user.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @speaker.url %>
</p>


<% if @speaker.slides.present? %> 
  <p>
    <strong>Slides:</strong>
    <%= GitHub::Markdown.render_gfm(@speaker.slides).html_safe %>
  </p>
<% end %>


<% if @speaker.past_talks.present? %>
<p>
  <strong>Past Talks:</strong>
  <%= GitHub::Markdown.render_gfm(@speaker.past_talks).html_safe %>
</p>
<% end %>

<% if @speaker.user.location.present? %>
<p>
  <strong>Location:</strong>
  <%= @speaker.user.location %>
</p>
<% end %>

<%= link_to 'Edit', edit_speaker_path(@speaker) %> |
<%= link_to 'Back', speakers_path %>